name: code_beacon
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^2.1.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_screenutil: ^0.4.2
  flutter_spinkit: "^3.1.0"
  flutter_local_notifications: ^0.4.4+2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  fonts:
  - family: MyIcon
    fonts:
      - asset: lib/icons/iconfont.ttf
  - family: siyuan
    fonts:
      - asset: fonts/SourceHanSansSC-Bold.otf
      - asset: fonts/SourceHanSansSC-Light.otf
      - asset: fonts/SourceHanSansSC-Normal.otf
      - asset: fonts/SourceHanSansSC-Regular.otf

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - lib/image/bkg.png
    - lib/image/room_choose_bar.png
    - lib/image/room_choose_bedroom.png
    - lib/image/room_choose_bedroom02.png
    - lib/image/room_choose_cookroom.png
    - lib/image/room_choose_hall.png
    - lib/image/tx.png
    - lib/image/0.png
    - lib/image/1.png
    - lib/image/2.png
    - lib/image/3.png
    - lib/image/4.png
    - lib/image/5.png
    - lib/image/6.png
    - lib/image/7.png
    - lib/image/8.png
    - lib/image/9.png
    - lib/image/10.png
    - lib/image/11.png
    - lib/image/12.png
    - lib/image/13.png
    - lib/image/14.png
    - lib/image/15.png
    - lib/image/16.png
    - lib/image/17.png
    - lib/image/18.png
    - lib/image/19.png
    - lib/image/20.png
    - lib/image/21.png
    - lib/image/22.png
    - lib/image/23.png
    - lib/image/24.png
    - lib/image/25.png
    - lib/image/26.png
    - lib/image/27.png
    - lib/image/28.png
    - lib/image/29.png
    - lib/image/30.png
    - lib/image/31.png
    - lib/image/32.png
    - lib/image/33.png
    - lib/image/34.png
    - lib/image/35.png
    - lib/image/36.png
    - lib/image/37.png
    - lib/image/38.png
    - lib/image/99.png
    - lib/image/null.png
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
